hotels/urls.py
from django.conf.urls import patterns,url
from hotels import views


urlpatterns = patterns('',

	url(r'^index/$',views.index,name='index'),

	url(r'^index/searchHotel/$',views.searchHotel,name='searchHotel'),

	url(r'^index/(?P<hotel_id>\d+)/checkRoom/$',views.checkRoom,name='checkRoom'),

	url(r'^index/(?P<hotel_id>\d+)/confirm/$',views.confirm,name='confirm'),

	url(r'^index/(?P<hotel_id>\d+)/success/$',views.success,name='success'),
	
	url(r'^index/searchHotel/sortHotels/(?P<by>\w+)$',views.sortHotels,name='sortHotels'),
)

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^hotels/',include('hotels.urls',namespace="hotels")),
)

hotels/models.py
from django.db import models

class Location(models.Model):
    country = models.CharField(max_length = 30)
    city = models.CharField(max_length=60)
    province = models.CharField(max_length=30)
    
    def __unicode__(self):
        return self.city

class Hotel(models.Model):
    """model of hotels"""
    name = models.CharField(max_length = 30)
    star = models.IntegerField()
    address = models.CharField(max_length=50)
    description = models.TextField()
    located  = models.ForeignKey(Location)

    def __unicode__(self):
        return self.name


class Room(models.Model):
    adult = models.IntegerField()  
    children = models.IntegerField()
    belongto = models.ForeignKey(Hotel)
    price = models.FloatField()
    roomNumber = models.IntegerField()

    def __unicode__(self):
        return 'adult: %s, children: %s' % (self.adult, self.children)

class Client(models.Model):
    smoking = models.BooleanField()
    firstname = models.CharField(max_length = 20)
    lastname = models.CharField(max_length = 20)
    requirement = models.TextField()
    def __unicode__(self):
        return self.firstname

class Order(models.Model):
    checkin = models.DateField()
    checkout = models.DateField()
    total  = models.FloatField()
    date = models.DateTimeField('Order Date') #create order by date
    client = models.ForeignKey(Client)
    code = models.CharField(max_length=45)
    def __unicode__(self):
        return unicode(self.checkin)

class Booked(models.Model):
    room = models.ForeignKey(Room)
    order = models.ForeignKey(Order)
    def __unicode__(self):
        return unicode(self.room) + ' ' + unicode(self.order)

hotels/views.py
from django.shortcuts import render_to_response,get_object_or_404
from django.core.context_processors import csrf
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import requires_csrf_token
from django.http import HttpResponse,Http404
from django.template import Context,loader
from django.core.cache import get_cache
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
import random

from hotels.models import Hotel,Location,Room,Client,Booked,Order

# Create your views here.
@requires_csrf_token
def index(request):
	context = {}
	context.update(csrf(request))
	return render_to_response('hotels/index.html',context)

@csrf_exempt
def searchHotel(request):
	key = request.POST['city']
	check_in_time = request.POST['checkin']
	check_out_time = request.POST['checkout']
	try:
		city_searched = Location.objects.get(city=key)
	except (KeyError, Location.DoesNotExist):
		city_list = Location.objects.all()
		print(city_list)
		if(len(city_list)>10):
			city_list_get = city_list[0:10]
		else:
			city_list_get = city_list
		context = Context({
			'city_list_get':city_list_get,
			'check_in_time':check_in_time,
			'check_out_time':check_out_time,
			})
		return render_to_response('hotels/recommendCity.html',context)
	else:
		hotel_list = Hotel.objects.filter(located_id=city_searched.id)
		context = Context({
			'hotel_list':hotel_list,
			'key':key,
			'check_in_time':check_in_time,
			'check_out_time':check_out_time,
			})
	return render_to_response('hotels/chooseHotel.html',context)

@csrf_exempt
def checkRoom(request,hotel_id):
	error = 0
	p = get_object_or_404(Hotel,pk=hotel_id)
	hotel = Hotel.objects.get(id=hotel_id)
	hotel_name = hotel.name
	hotel_star = hotel.star
	city_name = request.POST['city']
	check_in_time = request.POST['checkin']
	check_out_time = request.POST['checkout']
	context = Context({
			'error':error,
			'hotel_name':hotel_name,
			'hotel_star':hotel_star,
			'city_name':city_name,
			'check_in_time':check_in_time,
			'check_out_time':check_out_time,
		})
	return render_to_response('hotels/chooseRoomType.html', context)

@csrf_exempt
def confirm(request,hotel_id):
	p = get_object_or_404(Hotel,pk=hotel_id)
	error = 0
	hotel = Hotel.objects.get(id=hotel_id)
	hotel_name = hotel.name
	hotel_star = hotel.star
	city_name = request.POST['city']
	check_in_time = request.POST['checkin']
	check_out_time = request.POST['checkout']
	room_total = request.POST['roomTotal']
	all_num = [[] for i in range(1,int(room_total)+1)]
	adults_num = []
	children_num = []
	number_get = []
	price_get = []
	room_id_get = []
	price_all = 0
	j_set = [0 for i in range(1,int(room_total)+1)]
	try:
		for i in range(1,int(room_total)+1):
			adults_num = request.POST['room_'+str(i)+'_adults']
			all_num[i-1].append(adults_num)
			children_num = request.POST['room_'+str(i)+'_children']
			all_num[i-1].append(children_num)
			room = Room.objects.filter(adult=adults_num,children=children_num,belongto_id=hotel_id)
			number_get = room[j_set[i-1]].roomNumber
			if(i>=2):
				print(all_num[i-2])
				for a in all_num[0:i-1]:
					if (number_get == a[2]):
						j_set[i-1] += 1
						number_get = room[j_set[i-1]].roomNumber
			room_id_get.append(room[j_set[i-1]].id)
			all_num[i-1].append(number_get)
			price_get = room[j_set[i-1]].price
			price_all += price_get
			all_num[i-1].append(price_get)

	except IndexError:
		error = 1
		print(error)
		context = Context({
			'error':error,
			'hotel_name':hotel_name,
			'hotel_star':hotel_star,
			'city_name':city_name,
			'check_in_time':check_in_time,
			'check_out_time':check_out_time,
		})
		return render_to_response('hotels/chooseRoomType.html',context)
	except ValueError:
		error = 1
		context = Context({
			'error':error,
			'hotel_name':hotel_name,
			'hotel_star':hotel_star,
			'city_name':city_name,
			'check_in_time':check_in_time,
			'check_out_time':check_out_time,
		})
		return render_to_response('hotels/chooseRoomType.html',context)
	context = Context({
		'hotel_name':hotel_name,
		'hotel_star':hotel_star,
		'city_name':city_name,
		'check_in_time':check_in_time,
		'check_out_time':check_out_time,
		'all_num':all_num,
		'price_all':price_all,
		'room_id_get':room_id_get
	})
	return render_to_response('hotels/confirmReservation.html',context)

@csrf_exempt
def success(request,hotel_id):
	p = get_object_or_404(Hotel,pk=hotel_id)

	price_all = request.POST['price_all']
	check_in_time = request.POST['checkin']
	check_out_time = request.POST['checkout']
	client_firstname = request.POST['firstname']
	client_lastname = request.POST['lastname']
	client_require = request.POST['requirement']
	client_smoking = request.POST['smoking']

	client = Client(smoking=client_smoking,firstname=client_firstname,lastname=client_lastname,requirement=client_require)
	client.save()

	client_id = client.id
	order_code = str(random.randint(10000000,99999999))
	order = Order(checkin=check_in_time,checkout=check_out_time,total=price_all,date=timezone.now(),client_id=client_id,code=order_code)
	order.save()
	order_id = order.id
	num_all = request.POST['room_all']
	s = num_all[1:(len(num_all)-2)]
	order_id_set = s.split('L,')
	for i in range(0,len(order_id_set)):
		booked = Booked(room_id=int(order_id_set[i]),order_id=order_id)
		booked.save()
	context = Context({
			'order_code':order_code,
		})
	return render_to_response('hotels/success.html',context)

@csrf_exempt
def sortHotels(request, by):
	key = request.POST['city']
	check_in_time = request.POST['checkin']
	check_out_time = request.POST['checkout']
	city_searched = Location.objects.get(city=key)
	print check_out_time
	if(by =="star"):
		hotel_list = Hotel.objects.filter(located_id=city_searched.id).order_by("-star")
	elif(by == "name"):
		hotel_list = Hotel.objects.filter(located_id=city_searched.id).order_by("name")
	return render_to_response('hotels/getHotelList.html', locals())

hotels/templates/hotels/chooseHotel.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title>Choose Hotel</title>
    <link rel="stylesheet" href="{% static 'hotels/css/style.css' %}" />
</head>
<body>
    <div id="header">
        <h1>Welcome to Reserver Hotel</h1>
    </div>
    <div id="step">
        <span id="search_step">Search ></span>
        <span class="current" id="choose_hotel_step">Choose Hotel ></span>
        <span id="choose_room_type_step">Choose Room Type ></span>
        <span id="confirm_step">Confirm Reservation</span>
    </div>
    <div id="context">
        <div id="summary">
            <h2>Summary</h2>
            <table class="well-table">
                <tr>
                    <td>City</td>
                    <td>{{ key }}</td>
                </tr>
                <tr>
                    <td>Check in</td>
                    <td>{{ check_in_time}}</td>
                </tr>
                <tr>
                    <td>Check out</td>
                    <td>{{ check_out_time}}</td>
                </tr>
            </table>
        </div>
        <p><a href="{% url 'hotels:index'  %}"><-Search again</a></p>
        <div id="searchResult">
            <h2>Search Result</h2>
            <div id="sortBy">
                Sort Result By:
                <input id="star" type="radio" name="sortBy"/>
                <label for="star">High Star</label>
                <input id="name" type="radio" name="sortBy"/>
                <label for="name">Name</label>
            </div>
            <table id="hotelList" class="well-table">
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
                {% if hotel_list %}
                    {% for hotel in hotel_list %}
                    <tr>
                        <td>{{ hotel.name }},{{ key }}({{ hotel.star }}*)</td> 
                        <td><a class="continue" data-hotelId="{{hotel.id}}" href="#">Continue-></a></td>
                    {% endfor %}
                    </tr>
                {% else %}
                    <p>No hotels are available.</p>
                {% endif %}
            </table>
        </div>
    </div> 

    <form id="virtual" style="display:none" method="POST">
        <table class="well-table">
            <tr>                   
                <td><input id="city" type="text" name="city" value="{{ key }}"/></td>
            </tr>
            <tr>
                <td><input name="checkin" id="checkin" type="date" value="{{ check_in_time}}"/></td>
            </tr>
            <tr>
                <td><input name="checkout" id="checkout" type="date" value="{{ check_out_time }}"/></td>
            </tr>
            <tr>
                <td><input id="submit" type="submit" value="Submit" style="display:none"/></td>
                <td></td>
            </tr>
        </table>
    </form>

    <script type="text/javascript" src="{% static 'hotels/js/common.js' %}"></script>
    <script type="text/javascript" src="{% static 'hotels/js/ajax.js' %}"></script>
</body>
</html>

hotels/templates/hotels/chooseRoomType.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title>Choose Room Type</title>
    <link rel="stylesheet" href="{% static 'hotels/css/style.css' %}" />
</head>
<body>
    <div id="header">
        <h1>Welcome to Reserver Hotel</h1>
    </div>
    <div id="step">
        <span id="search_step">Search ></span>
        <span id="choose_hotel_step">Choose Hotel ></span>
        <span class="current" id="choose_room_type_step">Choose Room Type ></span>
        <span id="confirm_step">Confirm Reservation</span>
    </div>
    <div id="context">
        <div id="summary">
            <h2>Summary</h2>
            <table class="well-table">
                <tr>
                    <td>Hotel Name</td>
                    <td>{{ hotel_name }},{{ city_name }}({{ hotel_star }}*)</td>
                </tr>
                <tr>
                    <td>City</td>
                    <td>{{ city_name }}</td>
                </tr>
                <tr>
                    <td>Check in</td>
                    <td>{{ check_in_time }}</td>
                </tr>
                <tr>
                    <td>Check out</td>
                    <td>{{ check_out_time }}</td>
                </tr>
            </table>
        </div>
        <div id="ChooseRoomType">
            <h2>Choose Room Type</h2>

            <form action="../confirm/" method="post">
                <table class="well-table">
                    <tr>
                        <td>Rooms <input id="roomTotal" type="number" value="1" name="roomTotal"/></td>
                        <td>Room 1</td>
                        <td>Adults<input type="number" name="room_1_adults"/></td>
                        <td>Children <input type="number" name="room_1_children"/></td>
                        <input id="city" type="text" name="city" value="{{ city_name }}" style="display:none"/>
                        <input name="checkin" id="checkin" type="date" value="{{ check_in_time}}" style="display:none"/>
                        <input name="checkout" id="checkout" type="date" value="{{ check_out_time }}" style="display:none"/>
                    </tr>
                </table>
                <input id="submit" type="submit" style="display: none"/>
            </form>
        </div>
        {% if error == 1 %}
        <div class="error" style="display:display">
            <p>Sorry, there some room types we can't match</p>
        </div>
        {% endif %}
        <p><a id="back" href="#"><-Back</a> <a id="submitRoomType" href="##" style="float: right">Continue-></a></p>
    </div>
    <script type="text/javascript" src="{% static 'hotels/js/common.js' %}"></script>
</body>
</html>

hotels/templates/hotels/confirmReservation.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title>Confirm Reservation</title>
    <link rel="stylesheet" href="{% static 'hotels/css/style.css' %}" />
</head>
<body>
    <div id="header">
        <h1>Welcome to Reserver Hotel</h1>
    </div>
    <div id="step">
        <span id="search_step">Search ></span>
        <span id="choose_hotel_step">Choose Hotel ></span>
        <span id="choose_room_type_step">Choose Room Type ></span>
        <span class="current" id="confirm_step">Confirm Reservation</span>
    </div>
    <div id="context">
        <div id="summary">
            <h2>Summary</h2>
            <table class="well-table">
                <tr>
                    <td>Hotel Name</td>
                    <td>{{ hotel_name }},{{ city_name }}({{ hotel_star }}*)</td>
                </tr>
                <tr>
                    <td>City</td>
                    <td>{{ city_name }}</td>
                </tr>
                <tr>
                    <td>Check in</td>
                    <td>{{ check_in_time }}</td>
                </tr>
                <tr>
                    <td>Check out</td>
                    <td>{{ check_out_time }}</td>
                </tr>
            </table>
        </div>
        <div id="billingInformation">
            <h2>Billing Information</h2>
            <table class="well-table">
                <tr>
                    <th>Room Type</th>
                    <th>Room No.</th>
                    <th>Room Price</th>
                </tr>
                {% for all in all_num %}
                <tr>
                    <td>{{ all.0 }} Adults,{{ all.1}} Children</td> 
                    <td>{{ all.2 }}</td>
                    <td>${{ all.3 }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <th>Total</th>
                    <td></td>
                    <td>${{ price_all }}</td>
                </tr>
            </table>
        </div>
        <div id="confirmReservation">
            <h2>Confirm Reservation</h2>

            <form action="../success/" method="post">
                <table class="well-table">
                    <tr>
                        <td>Firstname</td>
                        <td><input type="text" name="firstname"/></td>
                    </tr>
                    <tr>
                        <td>Lastname</td>
                        <td><input name="lastname" type="text"/></td>
                    </tr>
                    <tr>
                        <td>Special requirement</td>
                        <td><textarea name="requirement" id="" cols="80" rows="10"></textarea></td>
                    </tr>
                    <tr>
                        <td>Smoking</td>
                        <td>Yes<input type="radio" name="smoking" value="1"/> No<input type="radio" name="smoking" value="0"/></td>
                    </tr>
                    <tr>
                        <td><input type="submit" value="submit"/></td>
                        <td></td>
                    </tr>
                </table>
                <input id="room_all" name="room_all" style="display:none" value="{{ room_id_get }}"/>
                <input id="price_all" name="price_all" style="display:none" value="{{ price_all }}"/>
                <input id="city" type="text" name="city" value="{{ city_name }}" style="display:none"/>
                <input name="checkin" id="checkin" type="date" value="{{ check_in_time}}" style="display:none"/>
                <input name="checkout" id="checkout" type="date" value="{{ check_out_time }}" style="display:none"/>
            </form>
        </div>
        <p><a id="back" href="../checkRoom/"><-Back</a></p>
    </div>
    <script type="text/javascript" src="{% static 'hotels/js/common.js' %}"></script>
</body>
</html>

hotels/templates/hotels/getHotelList.html
<tr>
    <th>Name</th>
    <th></th>
</tr>
{% if hotel_list %}
    {% for hotel in hotel_list %}
    <tr>
        <td>{{ hotel.name }},{{ key }}({{ hotel.star }}*)</td> 
        <td><a class="continue" data-hotelId="{{hotel.id}}" href="#">Continue-></a></td>
    {% endfor %}
    </tr>
{% else %}
    <p>No hotels are available.</p>
{% endif %}

hotels/templates/hotels/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title>Welcome to Reserver Hotel</title>
    <link rel="stylesheet" href="{% static 'hotels/css/style.css' %}" />
</head>
<body>
    <div id="header">
        <h1>Welcome to Reserver Hotel</h1>
    </div>
    <div id="step">
        <span class="current" id="search_step">Search ></span>
        <span id="choose_hotel_step">Choose Hotel ></span>
        <span id="choose_room_type_step">Choose Room Type ></span>
        <span id="confirm_step">Confirm Reservation</span>
    </div>
    <div id="searchHotel">
            <form id="search" action="searchHotel/" method="post">{% csrf_token %}
                <h2>Search Hotel</h2>
                <table class="well-table">
                    <tr>
                        <td><label for="city">City</label></td>
                        <td><input id="city" type="text" name="city"/></td>
                    </tr>
                    <tr>
                        <td><label for="checkin">Check in</label></td>
                        <td><input name="checkin" id="checkin" type="date"/></td>
                    </tr>
                    <tr>
                        <td><label for="checkout">Check out</label></td>
                        <td><input name="checkout" id="checkout" type="date"/></td>
                    </tr>
                    <tr>
                        <td><input type="submit" value="Submit"/></td>
                        <td></td>
                    </tr>
                </table>
            </form>
    </div>
    <script type="text/javascript" src="{% static 'hotels/js/common.js' %}"></script>
</body>
</html>

hotels/templates/hotels/recommendCity.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title>Recommended City</title>
    <link rel="stylesheet" href="{% static 'hotels/css/style.css' %}" />
</head>
<body>
<div id="header">
    <h1>Welcome to Reserver Hotel</h1>
</div>
<div id="context">
    <div class="error">
        <p>Sorry, City name is not found, you can see some hot cities we recommend.<p>
    </div>
    <p><a id="back" href="../checkRoom/"><-Back</a></p>
    <div id="recommendedCity">
        <h2>Recommend City</h2>
        <table class="well-table">
            <tr>
                <th>Hot City</th>
                <th>Country</th>
                <th>Province</th>
            </tr>
            {% if city_list_get %}
                {% for city in city_list_get %}
                <tr>
                    <td><a class="continue" data-hotelId="{{hotel.id}}" href="#">{{ city.city }}</a></td>
                    <td>{{ city.country }}</td>
                    <td>{{ city.province}}</td>
                </tr>
                {% endfor %}
            {% else %}
                <p>No city recommend</p>
            {% endif %}
        </table>
    </div>
</div>
<form id="virtual_ano" action="../searchHotel/" method="post" style="display:none" method="POST">
    <table class="well-table">
        <tr>                   
            <td><input id="city" type="text" name="city" value="1"/></td>
        </tr>
        <tr>
            <td><input name="checkin" id="checkin" type="date" value="{{ check_in_time}}"/></td>
        </tr>
        <tr>
            <td><input name="checkout" id="checkout" type="date" value="{{ check_out_time }}"/></td>
        </tr>
        <tr>
            <td><input id="submit" type="submit" value="Submit" style="display:none"/></td>
        <td></td>
        </tr>
    </table>
</form>
<script type="text/javascript" src="{% static 'hotels/js/common.js' %}"></script>
</body>
</html>

hotels/templates/hotels/success.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title>Reserve Hotel Successful</title>
    <link rel="stylesheet" href="{% static 'hotels/css/style.css' %}" />
</head>
<body>
    <div id="header">
        <h1>Welcome to Reserver Hotel</h1>
    </div>

    <div id="success">
        <h2>Reserve Hotel Successful</h2>
        <p>Your order number is <span id="orderNumber">{{ order_code }}</span>, please note down the number, you will be asked the order number when you go to the hotel.<p>
    </div>
</body>
</html>